---
- name: Setup Apache server on myservers
  hosts: ansible-demo
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    - name: Ensure apache2 is running
      systemd:
        name: apache2
        state: started
        enabled: yes
    - name: Create a Hello World HTML page
      copy:
        dest: /var/www/html/index.html
        content:  |
          <!DOCTYPE html>
          <html>
          <head>
             <title>Hello World</title>
          </head>
          <body>
            <h1>Hello World</h1>
          </body>
          </html>
        owner: www-data
        group: www-data
        mode: '0644'