---
- name: Install Apache on Amazon Linux
  hosts: amazon_linux
  become: yes
  tasks:
    - name: Update the package repository
      yum:
        name: '*'
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start Apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Ensure firewall allows HTTP traffic
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == "RedHat"

