---
- hosts: all 
  user: ansible 
  become: yes 
  become_method: sudo 
  become_user: root
  tasks:
    - name: Install Apache packages
      yum:
        name: httpd
        state: present

    - name: Ensure httpd is running 
      service:
        name: httpd
        state: started

    - name: Open port 80 for HTTP access 
      firewalld:
        service: http 
        permanent: true 
        state: enabled

    - name: Restart the firewalld service to load in the firewall changes 
      service:
        name: firewalld
        state: restarted  # Corrected from 'pentfted' to 'restarted'

    - name: Create the index.html file
      copy:  # Corrected from 'сору' to 'copy'
        content: "<h1>Welcome to my web server</h1>"  # Corrected syntax
        dest: /var/www/html/index.html  # Corrected destination path
        mode: '0644'
        owner: apache  # Corrected from 'oners' to 'owner'
        group: apache

